"""empty message

Revision ID: 3db8fb5d86cf
Revises: 
Create Date: 2024-05-04 23:56:34.763185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db8fb5d86cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=528), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('token_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('dream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dream', sa.String(length=6000), nullable=True),
    sa.Column('exclusivity', sa.Enum('PUBLIC', 'EXCLUSIVE', 'PRIVATE', name='exclusivity'), nullable=True),
    sa.Column('sleep_start', sa.String(), nullable=True),
    sa.Column('sleep_end', sa.String(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('log_date', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('who_liked', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dream', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dream_keywords'), ['keywords'], unique=False)
        batch_op.create_index(batch_op.f('ix_dream_log_date'), ['log_date'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=6000), nullable=True),
    sa.Column('log_date', sa.DateTime(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_log_date'), ['log_date'], unique=False)

    op.create_table('interpretation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interpretation', sa.String(length=6000), nullable=True),
    sa.Column('log_date', sa.DateTime(), nullable=True),
    sa.Column('dream_id', sa.Integer(), nullable=True),
    sa.Column('exclusivity', sa.Enum('PUBLIC', 'EXCLUSIVE', 'PRIVATE', name='exclusivity'), nullable=True),
    sa.Column('interpreter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dream_id'], ['dream.id'], ),
    sa.ForeignKeyConstraint(['interpreter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interpretation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interpretation_log_date'), ['log_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interpretation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interpretation_log_date'))

    op.drop_table('interpretation')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_log_date'))

    op.drop_table('message')
    with op.batch_alter_table('dream', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dream_log_date'))
        batch_op.drop_index(batch_op.f('ix_dream_keywords'))

    op.drop_table('dream')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
