"""empty message

Revision ID: 4d14feb0bd09
Revises: dd64d51004f4
Create Date: 2024-05-05 00:15:20.921179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d14feb0bd09'
down_revision = 'dd64d51004f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_dreams', sa.ARRAY(sa.Integer()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('liked_dreams')

    # ### end Alembic commands ###
