"""empty message

Revision ID: 5760653212e2
Revises: 665374426365
Create Date: 2024-05-02 18:59:07.686999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5760653212e2'
down_revision = '665374426365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('message_recipient_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('message_sender_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_foreign_key('message_sender_id_fkey', 'user', ['sender_id'], ['id'])
        batch_op.create_foreign_key('message_recipient_id_fkey', 'user', ['recipient_id'], ['id'])

    # ### end Alembic commands ###
