"""empty message

Revision ID: 623f2462546c
Revises: 443b5c44b836
Create Date: 2024-05-03 02:00:02.795449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '623f2462546c'
down_revision = '443b5c44b836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('ix_message_log_date')

    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(length=6000), autoincrement=False, nullable=True),
    sa.Column('log_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name='message_recipient_id_fkey'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='message_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_pkey')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index('ix_message_log_date', ['log_date'], unique=False)

    # ### end Alembic commands ###
