"""empty message

Revision ID: 79d65bfd05d0
Revises: e166b714e65e
Create Date: 2024-05-04 02:10:11.655599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d65bfd05d0'
down_revision = 'e166b714e65e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_likes', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_likes'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dream', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_likes')

    # ### end Alembic commands ###
