"""dream table

Revision ID: c9512435af63
Revises: b6dee25533f2
Create Date: 2024-04-24 23:01:07.039072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9512435af63'
down_revision = 'b6dee25533f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dream', sa.String(length=6000), nullable=True),
    sa.Column('dream_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dream', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dream_dream_date'), ['dream_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dream', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dream_dream_date'))

    op.drop_table('dream')
    # ### end Alembic commands ###
