"""empty message

Revision ID: f3a791f86574
Revises: 79d65bfd05d0
Create Date: 2024-05-04 02:23:05.982198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a791f86574'
down_revision = '79d65bfd05d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dream', schema=None) as batch_op:
        batch_op.drop_constraint('dream_user_likes_fkey', type_='foreignkey')
        batch_op.drop_column('user_likes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_likes', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('dream_user_likes_fkey', 'user', ['user_likes'], ['username'])

    # ### end Alembic commands ###
